### ISSUE TITLE
Error on Session End

### ISSUE THREAD

**Issue by tomjackman** [tomjackman/rre-spec#8]
`
Caught exception: TypeError: this.ee._events.hasOwnProperty is not a function                                           TypeError: this.ee._events.hasOwnProperty is not a function                                                                 at Ultron.remove (C:\Users\user\Downloads\spectator_2018-08-24\dev\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\ultron\index.js:80:27)                                                                            at Ultron.destroy (C:\Users\user\Downloads\spectator_2018-08-24\dev\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\ultron\index.js:116:8)                                                                           at WebSocket.cleanupWebsocketResources (C:\Users\user\Downloads\spectator_2018-08-24\dev\node_modules\socket.io\node_modules\engine.io\node_modules\ws\lib\WebSocket.js:851:36)                                                                 at emitOne (events.js:121:20)                                                                                           at Socket.emit (events.js:211:7)                                                                                        at emitErrorNT (internal/streams/destroy.js:64:8)                                                                       at _combinedTickCallback (internal/process/next_tick.js:138:11)                                                         at process._tickCallback (internal/process/next_tick.js:180:9)   `

**Comment by tomjackman** [comment]
May be Firefrox related.

**Comment by tomjackman** [comment]
Caused by newer socket.io version, fixed in https://github.com/tomjackman/rre-spec/commit/13642e10380164bcad2b9b7647633275e0f58dcb
